export type GalleryMediaItem = {
  id: string
  type: 'image' | 'video'
  src: string
  thumbnail: string
  alt: string
  title: string
  category: string
  width: number
  height: number
  thumbnailWidth: number
  thumbnailHeight: number
  position: string
}

export const galleryItems: GalleryMediaItem[] = [
  {
    id: 'equipe-em-servico',
    type: 'image',
    src: '/images/trabalhos/equipe-em-servico-full.webp',
    thumbnail: '/images/trabalhos/equipe-em-servico.webp',
    alt: 'Dois profissionais da JS Venezianas trabalhando em uma veneziana instalada em um quarto',
    title: 'Equipe em serviço',
    category: 'Execução cuidadosa',
    width: 1600,
    height: 1200,
    thumbnailWidth: 1400,
    thumbnailHeight: 1050,
    position: '48% center',
  },
  {
    id: 'funcionamento-externo',
    type: 'video',
    src: '/videos/galeria/funcionamento-externo.mp4',
    thumbnail: '/images/galeria/funcionamento-externo-poster.webp',
    alt: 'Veneziana externa em funcionamento',
    title: 'Funcionamento externo',
    category: 'Veneziana em movimento',
    width: 540,
    height: 960,
    thumbnailWidth: 562,
    thumbnailHeight: 1000,
    position: 'center',
  },
  {
    id: 'veneziana-fechada',
    type: 'image',
    src: '/images/galeria/veneziana-fechada-full.webp',
    thumbnail: '/images/galeria/veneziana-fechada.webp',
    alt: 'Veneziana residencial fechada em uma janela',
    title: 'Veneziana fechada',
    category: 'Acabamento residencial',
    width: 1600,
    height: 1200,
    thumbnailWidth: 1000,
    thumbnailHeight: 750,
    position: 'center',
  },
  {
    id: 'detalhe-da-instalacao',
    type: 'image',
    src: '/images/trabalhos/detalhe-da-instalacao-full.webp',
    thumbnail: '/images/trabalhos/detalhe-da-instalacao.webp',
    alt: 'Veneziana branca integrada a uma janela de correr',
    title: 'Detalhe da instalação',
    category: 'Integração à esquadria',
    width: 1800,
    height: 2400,
    thumbnailWidth: 1050,
    thumbnailHeight: 1400,
    position: 'center',
  },
  {
    id: 'servico-em-execucao',
    type: 'video',
    src: '/videos/galeria/servico-em-execucao.mp4',
    thumbnail: '/images/galeria/servico-em-execucao-poster.webp',
    alt: 'Profissional trabalhando em uma veneziana ampla',
    title: 'Serviço em execução',
    category: 'Equipe em campo',
    width: 960,
    height: 432,
    thumbnailWidth: 1000,
    thumbnailHeight: 450,
    position: 'center',
  },
  {
    id: 'abertura-parcial',
    type: 'image',
    src: '/images/galeria/abertura-parcial-full.webp',
    thumbnail: '/images/galeria/abertura-parcial.webp',
    alt: 'Veneziana parcialmente aberta em uma porta de vidro',
    title: 'Abertura parcial',
    category: 'Controle de luz',
    width: 1600,
    height: 1200,
    thumbnailWidth: 1000,
    thumbnailHeight: 750,
    position: 'center',
  },
  {
    id: 'instalacao-em-andamento',
    type: 'image',
    src: '/images/galeria/instalacao-em-andamento-full.webp',
    thumbnail: '/images/galeria/instalacao-em-andamento.webp',
    alt: 'Profissional instalando uma veneziana em um ambiente residencial',
    title: 'Instalação em andamento',
    category: 'Trabalho no local',
    width: 1600,
    height: 1200,
    thumbnailWidth: 1000,
    thumbnailHeight: 750,
    position: 'center 42%',
  },
  {
    id: 'acionamento-por-controle',
    type: 'video',
    src: '/videos/galeria/acionamento-por-controle.mp4',
    thumbnail: '/images/galeria/acionamento-por-controle-poster.webp',
    alt: 'Veneziana sendo acionada por controle remoto',
    title: 'Acionamento por controle',
    category: 'Demonstração de funcionamento',
    width: 960,
    height: 432,
    thumbnailWidth: 1000,
    thumbnailHeight: 450,
    position: 'center',
  },
  {
    id: 'acabamento-externo',
    type: 'image',
    src: '/images/trabalhos/acabamento-externo-full.webp',
    thumbnail: '/images/trabalhos/acabamento-externo.webp',
    alt: 'Veneziana metálica vista pelo lado externo de uma parede revestida',
    title: 'Acabamento externo',
    category: 'Proteção e privacidade',
    width: 720,
    height: 1280,
    thumbnailWidth: 720,
    thumbnailHeight: 1280,
    position: 'center',
  },
  {
    id: 'resultado-no-ambiente',
    type: 'image',
    src: '/images/trabalhos/resultado-no-ambiente-full.webp',
    thumbnail: '/images/trabalhos/resultado-no-ambiente.webp',
    alt: 'Ambiente residencial com veneziana branca instalada em uma porta de vidro',
    title: 'Resultado no ambiente',
    category: 'Vista interna da instalação',
    width: 1600,
    height: 1200,
    thumbnailWidth: 1400,
    thumbnailHeight: 1050,
    position: 'center 45%',
  },
  {
    id: 'controle-de-luz',
    type: 'image',
    src: '/images/galeria/controle-de-luz-full.webp',
    thumbnail: '/images/galeria/controle-de-luz.webp',
    alt: 'Veneziana parcialmente aberta controlando a entrada de luz',
    title: 'Controle de luz',
    category: 'Abertura regulada',
    width: 1600,
    height: 1200,
    thumbnailWidth: 1000,
    thumbnailHeight: 750,
    position: 'center',
  },
  {
    id: 'resultado-em-movimento',
    type: 'video',
    src: '/videos/galeria/resultado-em-movimento.mp4',
    thumbnail: '/images/galeria/resultado-em-movimento-poster.webp',
    alt: 'Conjunto de venezianas funcionando em um ambiente amplo',
    title: 'Resultado em movimento',
    category: 'Demonstração no ambiente',
    width: 960,
    height: 432,
    thumbnailWidth: 1000,
    thumbnailHeight: 450,
    position: 'center',
  },
  {
    id: 'ajuste-em-andamento',
    type: 'image',
    src: '/images/galeria/ajuste-em-andamento-full.webp',
    thumbnail: '/images/galeria/ajuste-em-andamento.webp',
    alt: 'Profissional ajustando uma veneziana instalada',
    title: 'Ajuste em andamento',
    category: 'Execução no local',
    width: 1600,
    height: 1200,
    thumbnailWidth: 1000,
    thumbnailHeight: 750,
    position: 'center',
  },
  {
    id: 'esquadria-e-veneziana',
    type: 'image',
    src: '/images/trabalhos/esquadria-e-veneziana-full.webp',
    thumbnail: '/images/trabalhos/esquadria-e-veneziana.webp',
    alt: 'Veneziana cinza integrada a uma esquadria escura',
    title: 'Esquadria e veneziana',
    category: 'Integração ao ambiente',
    width: 900,
    height: 1600,
    thumbnailWidth: 787,
    thumbnailHeight: 1400,
    position: 'center',
  },
  {
    id: 'resultado-final',
    type: 'image',
    src: '/images/trabalhos/resultado-final-full.webp',
    thumbnail: '/images/trabalhos/resultado-final.webp',
    alt: 'Veneziana branca fechada em um vão amplo de vidro',
    title: 'Resultado final',
    category: 'Veneziana em vão amplo',
    width: 899,
    height: 1599,
    thumbnailWidth: 787,
    thumbnailHeight: 1400,
    position: 'center',
  },
]

const homeGalleryIds = [
  'equipe-em-servico',
  'resultado-no-ambiente',
  'detalhe-da-instalacao',
  'acabamento-externo',
  'esquadria-e-veneziana',
  'resultado-final',
]

export const homeGallery = homeGalleryIds.map(id => galleryItems.find(item => item.id === id)!)
